//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocabularyTest {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocabularyTest.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сокращённое наименование.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имена псевдонимов.
        /// </summary>
        internal static string AliasNames {
            get {
                return ResourceManager.GetString("AliasNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки препинания, концевые.
        /// </summary>
        internal static string ClosePunctuation {
            get {
                return ResourceManager.GetString("ClosePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие, управляющие.
        /// </summary>
        internal static string ControlSymbol {
            get {
                return ResourceManager.GetString("ControlSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы валют.
        /// </summary>
        internal static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки препинания, тире.
        /// </summary>
        internal static string DashPunctuation {
            get {
                return ResourceManager.GetString("DashPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числа, десятичные цифры.
        /// </summary>
        internal static string DecimalDigitNumber {
            get {
                return ResourceManager.GetString("DecimalDigitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление темы.
        /// </summary>
        internal static string DeleteTheme {
            get {
                return ResourceManager.GetString("DeleteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление урока.
        /// </summary>
        internal static string DeletingLesson {
            get {
                return ResourceManager.GetString("DeletingLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление части речи.
        /// </summary>
        internal static string DeletingWordType {
            get {
                return ResourceManager.GetString("DeletingWordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В каталоге {0} словари не найдены..
        /// </summary>
        internal static string DictNotFound {
            get {
                return ResourceManager.GetString("DictNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите сокращенное наименование части речи.
        /// </summary>
        internal static string EnterAbbreviation {
            get {
                return ResourceManager.GetString("EnterAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки словаря..
        /// </summary>
        internal static string ErrorLoadDict {
            get {
                return ResourceManager.GetString("ErrorLoadDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке одного из дополений..
        /// </summary>
        internal static string ErrorLoadingAddons {
            get {
                return ResourceManager.GetString("ErrorLoadingAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при открытии файла {0}..
        /// </summary>
        internal static string ErrorOpen {
            get {
                return ResourceManager.GetString("ErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \dictionaries.xcu.
        /// </summary>
        internal static string FileDescriptionXCU {
            get {
                return ResourceManager.GetString("FileDescriptionXCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \description.xml.
        /// </summary>
        internal static string FileDescriptionXML {
            get {
                return ResourceManager.GetString("FileDescriptionXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игнорировать эту ошибку..
        /// </summary>
        internal static string IgnoreError {
            get {
                return ResourceManager.GetString("IgnoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль введен неверно..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урок.
        /// </summary>
        internal static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уроки.
        /// </summary>
        internal static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буквы, в нижнем регистре.
        /// </summary>
        internal static string LetterLowerCase {
            get {
                return ResourceManager.GetString("LetterLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буквы, модификаторы.
        /// </summary>
        internal static string LetterModify {
            get {
                return ResourceManager.GetString("LetterModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числа, буквы.
        /// </summary>
        internal static string LetterNumber {
            get {
                return ResourceManager.GetString("LetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буквы, другие.
        /// </summary>
        internal static string LetterOther {
            get {
                return ResourceManager.GetString("LetterOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буквы, в верхнем регистре.
        /// </summary>
        internal static string LetterUpperCase {
            get {
                return ResourceManager.GetString("LetterUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Математические символы.
        /// </summary>
        internal static string MathSymbol {
            get {
                return ResourceManager.GetString("MathSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы модификации.
        /// </summary>
        internal static string ModifierSymbol {
            get {
                return ResourceManager.GetString("ModifierSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на oor:name.
        /// </summary>
        internal static string NodeAttributeName {
            get {
                return ResourceManager.GetString("NodeAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionaries.
        /// </summary>
        internal static string NodeDictionaries {
            get {
                return ResourceManager.GetString("NodeDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на display-name.
        /// </summary>
        internal static string NodeDisplayName {
            get {
                return ResourceManager.GetString("NodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ServiceManager.
        /// </summary>
        internal static string NodeServiceManager {
            get {
                return ResourceManager.GetString("NodeServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметки, без промежутков.
        /// </summary>
        internal static string NonSpacingMark {
            get {
                return ResourceManager.GetString("NonSpacingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечания.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки препинания, открывающие.
        /// </summary>
        internal static string OpenPunctuation {
            get {
                return ResourceManager.GetString("OpenPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие не присвоенные.
        /// </summary>
        internal static string OtherNotAssigned {
            get {
                return ResourceManager.GetString("OtherNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числа, другие.
        /// </summary>
        internal static string OtherNumber {
            get {
                return ResourceManager.GetString("OtherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки препинания, другие.
        /// </summary>
        internal static string OtherPunctuation {
            get {
                return ResourceManager.GetString("OtherPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы, другие.
        /// </summary>
        internal static string OtherSymbol {
            get {
                return ResourceManager.GetString("OtherSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировка.
        /// </summary>
        internal static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить урок?.
        /// </summary>
        internal static string QuestionDeleteLesson {
            get {
                return ResourceManager.GetString("QuestionDeleteLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить тему?.
        /// </summary>
        internal static string QuestionDeleteTheme {
            get {
                return ResourceManager.GetString("QuestionDeleteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить часть речи?.
        /// </summary>
        internal static string QuestionDeleteWordType {
            get {
                return ResourceManager.GetString("QuestionDeleteWordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо вести имя файла..
        /// </summary>
        internal static string ReguiredFileName {
            get {
                return ResourceManager.GetString("ReguiredFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделители, пробелы.
        /// </summary>
        internal static string SpaceSeparator {
            get {
                return ResourceManager.GetString("SpaceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий: {0}.
        /// </summary>
        internal static string StatusComment {
            get {
                return ResourceManager.GetString("StatusComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произношение: {0}.
        /// </summary>
        internal static string StatusPronunciation {
            get {
                return ResourceManager.GetString("StatusPronunciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часть речи: {0}.
        /// </summary>
        internal static string StatusWordType {
            get {
                return ResourceManager.GetString("StatusWordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать пользователя..
        /// </summary>
        internal static string UserNeeded {
            get {
                return ResourceManager.GetString("UserNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировка словарного запаса.
        /// </summary>
        internal static string VocabularyTest {
            get {
                return ResourceManager.GetString("VocabularyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Части речи.
        /// </summary>
        internal static string WordTypes {
            get {
                return ResourceManager.GetString("WordTypes", resourceCulture);
            }
        }
    }
}
